version: 1.0.{build}
branches:
  only:
  - master
skip_tags: true

image:
- Visual Studio 2019

install:
- cmd: >-
    git submodule update --init --depth 1
    
build_script:
- cmd: >-
      call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat" x64

      msbuild duckstation.sln -t:Build -p:Platform=x64;Configuration=ReleaseLTCG

      rm -f bin/x64/*.pdb bin/x64/*.exp bin/x64/*.lib bin/x64/*.iobj bin/x64/*.ipdb

      rm -f bin/x64/common-tests*

      cp -a data/* bin/x64

      "C:\Program Files\7-Zip\7z.exe" a -r duckstation-win64-release.7z ./bin/x64/*

      appveyor PushArtifact duckstation-win64-release.7z


test: off
