name: Flathub Publish

on:
  workflow_dispatch:
    inputs:
      flathub_branch:
        description: "Flathub branch to push to"
        required: true
        default: "stable"
        type: "choice"
        options:
          - "stable"
          - "beta"

jobs:
  linux-appimage:
    name: ğŸ§ Linux AppImage
    uses: "./.github/workflows/linux-appimage-build.yml"
  linux-cross-appimage:
    name: ğŸ§ Linux Cross-Compiled AppImage
    uses: "./.github/workflows/linux-cross-appimage-build.yml"
  linux-flatpak:
    name: ğŸ“¦ Build Flatpak
    needs: [linux-appimage, linux-cross-appimage]
    uses: "./.github/workflows/linux-flatpak-build.yml"
    with:
      flathub_publish: true
      flathub_branch: ${{ inputs.flathub_branch }}
    secrets: inherit
