name: Automated Builds

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - '**.md'
      - 'appveyor.yml'
      - 'scripts/*'
      - '.github/ISSUE_TEMPLATE/*'
  push:
    branches:
      - master
      - dev
    paths-ignore:
      - '**.md'
      - 'appveyor.yml'
      - 'scripts/*'
      - '.github/ISSUE_TEMPLATE/*'

jobs:
  windows:
    name: üíª Windows
    uses: "./.github/workflows/windows-build.yml"
  linux-appimage:
    name: üêß Linux AppImage
    uses: "./.github/workflows/linux-appimage-build.yml"
  linux-cross-appimage:
    name: üêß Linux Cross-Compiled AppImage
    uses: "./.github/workflows/linux-cross-appimage-build.yml"
  macos:
    name: üçé MacOS
    uses: "./.github/workflows/macos-build.yml"

  create-release:
    name: üì§ Create Release
    needs: [windows, linux-appimage, linux-cross-appimage, macos]
    runs-on: ubuntu-22.04
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/dev'
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v7
        with:
          path: ./artifacts/
          merge-multiple: true

      - name: Display Downloaded Artifacts
        run: find ./artifacts/ -type f | sort

      - name: Create Preview Release
        if: github.ref == 'refs/heads/master'
        uses: marvinpinto/action-automatic-releases@d68defdd11f9dcc7f52f35c1b7c236ee7513bcc1
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "preview"
          prerelease: true
          title: "Latest Preview Build"
          files: |
            ./artifacts/duckstation-windows-x64-release.zip
            ./artifacts/duckstation-windows-x64-release-symbols.zip
            ./artifacts/duckstation-windows-x64-sse2-release.zip
            ./artifacts/duckstation-windows-x64-sse2-release-symbols.zip
            ./artifacts/duckstation-windows-arm64-release.zip
            ./artifacts/duckstation-windows-arm64-release-symbols.zip
            ./artifacts/DuckStation-x64.AppImage
            ./artifacts/DuckStation-x64-SSE2.AppImage
            ./artifacts/DuckStation-arm64.AppImage
            ./artifacts/DuckStation-Mini-arm64.AppImage
            ./artifacts/DuckStation-armhf.AppImage
            ./artifacts/DuckStation-Mini-armhf.AppImage
            ./artifacts/duckstation-mac-release.zip

      - name: Create Rolling Release
        if: github.ref == 'refs/heads/dev'
        uses: marvinpinto/action-automatic-releases@d68defdd11f9dcc7f52f35c1b7c236ee7513bcc1
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Latest Rolling Release"
          files: |
            ./artifacts/duckstation-windows-x64-release.zip
            ./artifacts/duckstation-windows-x64-release-symbols.zip
            ./artifacts/duckstation-windows-x64-sse2-release.zip
            ./artifacts/duckstation-windows-x64-sse2-release-symbols.zip
            ./artifacts/duckstation-windows-arm64-release.zip
            ./artifacts/duckstation-windows-arm64-release-symbols.zip
            ./artifacts/DuckStation-x64.AppImage
            ./artifacts/DuckStation-x64-SSE2.AppImage
            ./artifacts/DuckStation-arm64.AppImage
            ./artifacts/DuckStation-Mini-arm64.AppImage
            ./artifacts/DuckStation-armhf.AppImage
            ./artifacts/DuckStation-Mini-armhf.AppImage
            ./artifacts/duckstation-mac-release.zip
